### ISSUE TITLE
FloatingPointError: Predicted boxes or scores contain Inf/NaN

### ISSUE THREAD

**Issue by anranbixin** [facebookresearch/adaptive_teacher#57]
Hello, could you please share the configuration file you ran out? I also had the following problems during the experiment (the problem occurred in the first iteration) : `FloatingPointError: Predicted boxes or scores contain Inf/NaN`. Training has diverged. After trying through the problem set, changing the weights and updating the virtual machine environment, the problem was still not resolved. What is your operating environment? I tried single gpu and multi-GPU (4). My experimental environment is python3.8,torch=1.9,cuda=11.6,detectron2=0.5. (#9 #12 )I tried the method in the two questions above the question,but still didn't solve the problem.My attempt was at voc2012 to clipart.

**Comment by huamiao1012** [comment]
I have the same question, and if the problem appears in the initial of experiment, may be you can try to install detectron2=0.3.

**Comment by ouyang11111** [comment]
> 

 my problem appears in the initial but my CUDA version are not support low version of detectron2 (<0.6 not support) .how to fix ?

**Comment by anranbixin** [comment]
I am renting a server, so I did not solve this problem, but detectron=0.3 is able to configure the corresponding operating environment. My environment is cude10.2, Python 3.8, and torch 1.7.

**Comment by ouyang11111** [comment]
> 

now i will seek for a rent too. for it has already waste me a few days .

**Comment by anranbixin** [comment]
You can use https://www.gpushare.com The above server, detectron=0.3, needs to be downloaded and installed by oneself. Other instructions can be used: 1 Pip install torch=1.7.0 torch vision=0.8.0 torch studio=0.7.0
2. pip install torch=1.7.0 torch vision=0.8.1 torch studio=0.7.0
(Because there may be an issue with the torch and torch vision versions here)
3. pip install prettytable
The machine can be either a TITAN X-12G * 1 card or a 2080 Ti-11G * 1 card

**Comment by anranbixin** [comment]
You can use https://www.gpushare.com/ The above server, detectron=0.3, needs to be downloaded and installed by oneself. Other instructions can be used: 
1. pip install torch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0
2. pip install torch==1.7.0 torchvision==0.8.1 torchaudio==0.7.0
(Because there may be an issue with the torch and torch vision versions here)

The machine can be either a TITAN X-12G * 1 card or a 2080 Ti-11G * 1 card

**Comment by ouyang11111** [comment]
> 

thanks i will try

**Comment by active-svg** [comment]
请问解决了吗，这个问题，Predicted boxes or scores contain Inf/NaN. Training has diverged.，是如何解决的

**Comment by ouyang11111** [comment]
我是租服务器解决的

一个老外给我的回复方案：

You can use&nbsp;https://www.gpushare.com/&nbsp;The above server, detectron=0.3, needs to be downloaded and installed by oneself. Other instructions can be used:

pip install torch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0

pip install torch==1.7.0 torchvision==0.8.1 torchaudio==0.7.0
(Because there may be an issue with the torch and torch vision versions here)

The machine can be either a TITAN X-12G * 1 card or a 2080 Ti-11G * 1 card



jianfeiou
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/adaptive_teacher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月19日(星期四) 下午4:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/adaptive_teacher] FloatingPointError: Predicted boxes or scores contain Inf/NaN (Issue #57)





 
请问解决了吗，这个问题，Predicted boxes or scores contain Inf/NaN. Training has diverged.，是如何解决的

**Comment by active-svg** [comment]
但是我装完detectron3之后又出现TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType错误，该怎么解决嘞
